namespace ICanRead.Domain.Entities;

/// <summary>What a code lets its holder do.</summary>
/// <remarks>
/// The purpose is part of what makes a code valid, not a label on it. Without
/// it, the code emailed to prove an address could be typed into the reset form
/// — which would turn "can receive mail here" into "can take this account over"
/// for anyone who happened to be holding one.
/// </remarks>
public enum AccountCodePurpose
{
    /// <summary>Sets a new password without signing in first.</summary>
    PasswordReset,

    /// <summary>Proves the reader can read mail at the address on the account.</summary>
    EmailVerification
}

/// <summary>
/// A one-time code emailed to a reader, for one purpose.
/// </summary>
/// <remarks>
/// <para>
/// A code the reader types, not a link they tap. The app has no website and no
/// deep-link setup, so a link would have nowhere to land; a six-digit code is
/// something a phone can accept on the screen the reader is already on.
/// </para>
/// <para>
/// Six digits is only a million guesses, which is why the code is useless on
/// its own: it lives for fifteen minutes, only the newest one for an account
/// and purpose is live at a time, and it is destroyed after
/// <see cref="MaxAttempts"/> wrong tries. The endpoint is rate limited on top of
/// that.
/// </para>
/// <para>
/// Only the hash is stored. A leaked database must not be a pile of usable
/// codes, and — as with refresh tokens — plain SHA-256 is enough because the
/// code is generated by us and is short-lived, not chosen by a person.
/// </para>
/// </remarks>
public class AccountCode
{
    /// <summary>Wrong tries this code survives before it is spent.</summary>
    public const int MaxAttempts = 5;

    /// <summary>How long a code stays usable after it is issued.</summary>
    public static readonly TimeSpan Lifetime = TimeSpan.FromMinutes(15);

    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public User? User { get; set; }

    public AccountCodePurpose Purpose { get; set; }

    /// <summary>Lowercase hex SHA-256 of the six digits that were emailed.</summary>
    public required string CodeHash { get; set; }

    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset ExpiresAt { get; set; }

    /// <summary>Set the moment the code is spent — successfully or not.</summary>
    public DateTimeOffset? ConsumedAt { get; set; }

    public int Attempts { get; set; }

    public bool IsLive(DateTimeOffset now) =>
        ConsumedAt is null && now < ExpiresAt && Attempts < MaxAttempts;
}
