namespace ICanRead.Domain.Entities;

/// <summary>
/// Which shelf a book sits on.
/// </summary>
/// <remarks>
/// There is deliberately no <c>Archived</c>. The client dropped it in favour of
/// pausing the plan, which is the same thing to a reader and already carries a
/// date. Adding it back here would let a device sync a status the app cannot
/// display. Stored as a string, so the numbers never drift from the client's.
/// </remarks>
public enum BookStatus
{
    Reading,
    Finished
}

/// <summary>
/// A book the reader is working through. The PDF itself never reaches here —
/// only what is needed to rebuild the plan on another device.
/// </summary>
public class Book : ISyncedEntity
{
    /// <summary>Generated by the client, so a book can be created offline.</summary>
    public Guid Id { get; set; }

    public Guid UserId { get; set; }
    public User? User { get; set; }

    public required string Title { get; set; }
    public string? Author { get; set; }

    /// <summary>Physical page count of the PDF, not the printed numbering.</summary>
    public int PageCount { get; set; }

    /// <summary>
    /// Added to a physical index to get the number printed on the page.
    /// Display only — every stored page number is physical.
    /// </summary>
    public int PageLabelOffset { get; set; }

    public BookStatus Status { get; set; } = BookStatus.Reading;

    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>Soft delete, so the tombstone can reach other devices.</summary>
    public DateTimeOffset? DeletedAt { get; set; }

    /// <inheritdoc />
    public DateTimeOffset ServerUpdatedAt { get; set; }

    public ICollection<BookFingerprint> Fingerprints { get; set; } = [];
    public ICollection<ReadingPlan> Plans { get; set; } = [];
}
