namespace ICanRead.Domain.Entities;

/// <summary>
/// A one-time code emailed to a reader who cannot get into their account.
/// </summary>
/// <remarks>
/// <para>
/// A code the reader types, not a link they tap. The app has no website and no
/// deep-link setup, so a link would have nowhere to land; a six-digit code is
/// something a phone can accept on the screen the reader is already on.
/// </para>
/// <para>
/// Six digits is only a million guesses, which is why the code is useless on
/// its own: it lives for fifteen minutes, only the newest one for an account is
/// live at a time, and it is destroyed after
/// <see cref="MaxAttempts"/> wrong tries. The endpoint is rate limited on top of
/// that.
/// </para>
/// <para>
/// Only the hash is stored. A leaked database must not be a pile of usable
/// codes, and — as with refresh tokens — plain SHA-256 is enough because the
/// code is generated by us and is short-lived, not chosen by a person.
/// </para>
/// </remarks>
public class PasswordResetCode
{
    /// <summary>Wrong tries this code survives before it is spent.</summary>
    public const int MaxAttempts = 5;

    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public User? User { get; set; }

    /// <summary>Lowercase hex SHA-256 of the six digits that were emailed.</summary>
    public required string CodeHash { get; set; }

    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset ExpiresAt { get; set; }

    /// <summary>Set the moment the code is spent — successfully or not.</summary>
    public DateTimeOffset? ConsumedAt { get; set; }

    public int Attempts { get; set; }

    public bool IsLive(DateTimeOffset now) =>
        ConsumedAt is null && now < ExpiresAt && Attempts < MaxAttempts;
}
