// <auto-generated />
using System;
using ICanRead.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICanRead.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908025809_AddSessionTombstone")]
    partial class AddSessionTombstone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ICanRead.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PageLabelOffset")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ServerUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ServerUpdatedAt");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.BookFingerprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ServerUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ServerUpdatedAt");

                    b.HasIndex("Sha256");

                    b.ToTable("book_fingerprints", (string)null);
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.ReadingLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("FromPage")
                        .HasColumnType("int");

                    b.Property<int>("PagesRead")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ReadDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ServerUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ToPage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerUpdatedAt");

                    b.HasIndex("PlanId", "ReadDate");

                    b.ToTable("reading_log", (string)null);
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.ReadingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EndPage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LastPageRead")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PagesPerDay")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PausedDays")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ServerUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StartPage")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TargetEndDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ServerUpdatedAt");

                    b.ToTable("reading_plans", (string)null);
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.ReadingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<int>("PagesShare")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ServerUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TimeOfDayMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("ServerUpdatedAt");

                    b.ToTable("reading_sessions", (string)null);
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasFilter("[GoogleSubject] IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.Book", b =>
                {
                    b.HasOne("ICanRead.Domain.Entities.User", "User")
                        .WithMany("Books")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.BookFingerprint", b =>
                {
                    b.HasOne("ICanRead.Domain.Entities.Book", "Book")
                        .WithMany("Fingerprints")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.ReadingLogEntry", b =>
                {
                    b.HasOne("ICanRead.Domain.Entities.ReadingPlan", "Plan")
                        .WithMany("Log")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.ReadingPlan", b =>
                {
                    b.HasOne("ICanRead.Domain.Entities.Book", "Book")
                        .WithMany("Plans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.ReadingSession", b =>
                {
                    b.HasOne("ICanRead.Domain.Entities.ReadingPlan", "Plan")
                        .WithMany("Sessions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ICanRead.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.Book", b =>
                {
                    b.Navigation("Fingerprints");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.ReadingPlan", b =>
                {
                    b.Navigation("Log");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ICanRead.Domain.Entities.User", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
